#put your docker-compose contents here and link the docker's port with your chosen external port!
version: "3.7"
services:
    casino:
        container_name: b01lers_casino
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "6789:5000"
