#put your docker-compose contents here and link the docker's port with your chosen external port!
version: "3"
services:
  texnically:
    container_name: texnically
    build:
      dockerfile: ./deploy/Dockerfile
      context: ../
    logging:
      driver: "json-file"
    ports:
      - "4001:4001"