version: "3.7"
services:
    pwnhub:
        container_name: pwnhub
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "6969:5000"